name: Download Google Sheets

on:
  workflow_dispatch:

jobs:
  build:
    name: Download Google Sheets
    runs-on: ubuntu-latest
    env:
      GAUTH_TYPE: ${{secrets.GAUTH_TYPE}}
      GAUTH_PROJECT_ID: ${{secrets.GAUTH_PROJECT_ID}}
      GAUTH_PRIVATE_KEY_ID: ${{secrets.GAUTH_PRIVATE_KEY_ID}}
      GAUTH_PRIVATE_KEY: ${{secrets.GAUTH_PRIVATE_KEY}}
      GAUTH_CLIENT_EMAIL: ${{secrets.GAUTH_CLIENT_EMAIL}}
      GAUTH_CLIENT_ID: ${{secrets.GAUTH_CLIENT_ID}}
      GAUTH_AUTH_URI: ${{secrets.GAUTH_AUTH_URI}}
      GAUTH_TOKEN_URI: ${{secrets.GAUTH_TOKEN_URI}}
      GAUTH_AUTH_PROVIDER_X509_CERT_URL: ${{secrets.GAUTH_AUTH_PROVIDER_X509_CERT_URL}}
      GAUTH_CLIENT_X509_CERT_URL: ${{secrets.GAUTH_CLIENT_X509_CERT_URL}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1   
      - name: Create ~/client_secret.json
        run: |
          echo $(cat <<-EOS
          {
            "type": "${{ secrets.GAUTH_TYPE }}",
            "project_id": "${{ secrets.GAUTH_PROJECT_ID }}",
            "private_key_id":"${{ secrets.GAUTH_PRIVATE_KEY_ID }}",
            "private_key": "${{ secrets.GAUTH_PRIVATE_KEY }}",
            "client_email": "${{ secrets.GAUTH_CLIENT_EMAIL }}",
            "client_id": "${{ secrets.GAUTH_CLIENT_ID }}",
            "auth_uri": "${{ secrets.GAUTH_AUTH_URI }}",
            "token_uri": "${{ secrets.GAUTH_TOKEN_URI }}",
            "auth_provider_x509_cert_url": "${{ secrets.GAUTH_AUTH_PROVIDER_X509_CERT_URL }}",
            "client_x509_cert_url": "${{ secrets.GAUTH_CLIENT_X509_CERT_URL }}"            
          }
          EOS
          ) > ~/.client_secret.json
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python
        run: python download_sheets.py

