name: download_r4

# Controls when the workflow will run
on:
  schedule:
    - cron: "*/10 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Download_R4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1   
      - name: run script
        run: ./download_r4.sh
      - name: commit & push
        run: |
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            echo change ditected update reposistory
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update"
            git push
          else
            echo no change
          fi
