name: Download Google Sheets and Output documents

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Download Google Sheets
    runs-on: ubuntu-latest
    env:
      GAUTH_TYPE: ${{secrets.GAUTH_TYPE}}
      GAUTH_PROJECT_ID: ${{secrets.GAUTH_PROJECT_ID}}
      GAUTH_PRIVATE_KEY_ID: ${{secrets.GAUTH_PRIVATE_KEY_ID}}
      GAUTH_PRIVATE_KEY: ${{secrets.GAUTH_PRIVATE_KEY}}
      GAUTH_CLIENT_EMAIL: ${{secrets.GAUTH_CLIENT_EMAIL}}
      GAUTH_CLIENT_ID: ${{secrets.GAUTH_CLIENT_ID}}
      GAUTH_AUTH_URI: ${{secrets.GAUTH_AUTH_URI}}
      GAUTH_TOKEN_URI: ${{secrets.GAUTH_TOKEN_URI}}
      GAUTH_AUTH_PROVIDER_X509_CERT_URL: ${{secrets.GAUTH_AUTH_PROVIDER_X509_CERT_URL}}
      GAUTH_CLIENT_X509_CERT_URL: ${{secrets.GAUTH_CLIENT_X509_CERT_URL}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1   
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Get Python version
        run: python -V
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: download sheets
        run: make raw_csv
      - name: Count changes
        id: changes
        run: |
          git add -N . # 新規ファイルを含める
          echo "::set-output name=count::$(git diff --name-only | wc -l)"   
      - name: make markdown and CSVs
        run: |
          make tables
          make markdown
        if: steps.changes.outputs.count > 0
      - name: make statistics
        run: make statistics
        if: steps.changes.outputs.count > 0
      - name: ouput docs(docx,pdf,draft docx, draft pdf)
        run: |
          make docs
          make draft_docs
        if: steps.changes.outputs.count > 0
      - name: deploy
        run: make deploy
        if: steps.changes.outputs.count > 0
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated from Google Sheet"
          git push
        if: steps.changes.outputs.count > 0
        


